<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Governors: Temperance</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="governors-temperance_files/libs/clipboard/clipboard.min.js"></script>
<script src="governors-temperance_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="governors-temperance_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="governors-temperance_files/libs/quarto-html/popper.min.js"></script>
<script src="governors-temperance_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="governors-temperance_files/libs/quarto-html/anchor.min.js"></script>
<link href="governors-temperance_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="governors-temperance_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="governors-temperance_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="governors-temperance_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="governors-temperance_files/libs/bootstrap/bootstrap-22d9d407b2aa3baf060e26cb929b2862.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Governors: Temperance</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-question" class="level2">
<h2 class="anchored" data-anchor-id="the-question">The Question</h2>
<p>Barfort, Klemmensen, and Larsen (2021) collected the lifespans of 3,587 candidates for US gubernatorial office going back to the 1800s, in order to estimate the causal effect of winning office on longevity. By comparing winners and losers of <em>close</em> elections — near coin flips — they argue the treatment is as good as randomly assigned. (See Gelman’s commentary on the paper, and the authors’ response, for a running argument about whether the headline estimate is believable.)</p>
<p>There are two scenarios. Focus on just one of them:</p>
<ul>
<li><p>Imagine you work for a life insurer, and want to forecast how long candidates for the US Senate might live based on their age, party, election result, and other variables.</p></li>
<li><p>Imagine you are a researcher. You want to know if winning candidates live longer. You are interested in candidates for any elected office — senate, governor, mayor, et cetera.</p></li>
</ul>
<p>The life insurer asks: How many years, on average, will this year’s US Senate candidates live after their election, given their age, party, and election result?</p>
<p>The researcher asks: What is the average causal effect of winning an election — for any elected office, from senator to governor to mayor — rather than losing it, on the number of years a candidate lives afterward?</p>
<p>Note that we use the same data, and the same fitted model, to help both people.</p>
<p>The setup chunk of this document carries forward the work from Wisdom and Courage: the close-election tibble <code>x</code> and the fitted model <code>fit_governors</code> are already built, so today starts at the answering.</p>
</section>
<section id="temperance" class="level2">
<h2 class="anchored" data-anchor-id="temperance">Temperance</h2>
<section id="predictions" class="level3">
<h3 class="anchored" data-anchor-id="predictions">Predictions</h3>
<p>Use <code>predictions(fit_governors)</code> to estimate the years lived after the election for individual candidates in the sample.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 254 × 24
   rowid estimate std.error statistic   p.value s.value conf.low conf.high state
   &lt;int&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;
 1     1     25.1      1.57     16.0  2.00e- 57   188.      22.0      28.2 Alab…
 2     2     23.2      1.53     15.1  1.66e- 51   169.      20.2      26.2 Alab…
 3     3     26.9      1.75     15.4  1.63e- 53   175.      23.5      30.4 Alas…
 4     4     39.5      1.84     21.4  4.74e-102   337.      35.9      43.1 Alas…
 5     5     23.8      1.30     18.3  1.81e- 74   245.      21.2      26.4 Alas…
 6     6     35.9      1.28     28.1  3.64e-174   576.      33.4      38.4 Alas…
 7     7     14.7      1.77      8.33 7.75e- 17    53.5     11.3      18.2 Alas…
 8     8     33.4      1.63     20.5  9.57e- 94   309.      30.2      36.6 Alas…
 9     9     16.7      1.80      9.27 1.83e- 20    65.6     13.2      20.3 Alas…
10    10     17.2      1.47     11.7  2.07e- 31   102.      14.3      20.1 Ariz…
# ℹ 244 more rows
# ℹ 15 more variables: year &lt;dbl&gt;, first_name &lt;chr&gt;, last_name &lt;chr&gt;,
#   party &lt;chr&gt;, sex &lt;chr&gt;, died &lt;date&gt;, status &lt;chr&gt;, win_margin &lt;dbl&gt;,
#   region &lt;chr&gt;, outcome &lt;chr&gt;, election_age &lt;dbl&gt;, death_age &lt;dbl&gt;,
#   lived_after &lt;dbl&gt;, election_result &lt;chr&gt;, df &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Use <code>avg_predictions(fit_governors, by = "election_result")</code> to estimate the average years lived after the election for winners and losers.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 9
  election_result estimate std.error statistic   p.value s.value conf.low
  &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1 Lose                27.2     1.03       26.3 1.48e-152    504.     25.2
2 Win                 29.6     0.963      30.7 2.40e-207    686.     27.7
# ℹ 2 more variables: conf.high &lt;dbl&gt;, df &lt;dbl&gt;</code></pre>
</div>
</div>
<p>What is the expected number of years lived after the election for a losing candidate (with 95% CI)?</p>
<p>A losing candidate is expected to live <strong>27.2 years</strong> after the election (95% CI: <strong>[25.2, 29.2]</strong>).</p>
<p>What is the expected number of years lived after the election for a winning candidate (with 95% CI)?</p>
<p>A winning candidate is expected to live <strong>29.6 years</strong> after the election (95% CI: <strong>[27.7, 31.5]</strong>).</p>
</section>
<section id="comparisons" class="level3">
<h3 class="anchored" data-anchor-id="comparisons">Comparisons</h3>
<p>Use <code>avg_comparisons(fit_governors, variables = "election_result")</code> to estimate the effect of winning on years lived after the election.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
  term  contrast estimate std.error statistic p.value s.value conf.low conf.high
  &lt;chr&gt; &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 elec… Win - L…     8.63      2.74      3.15 0.00163    9.26     3.26      14.0</code></pre>
</div>
</div>
<p>Why is the estimate from <code>avg_comparisons()</code> so much larger than the difference between the two group averages from <code>avg_predictions()</code>?</p>
<p>The difference between the group average predictions (2.4 years) is calculated using the observed values of the covariates in our sample, where winners and losers have different covariate distributions. Most importantly, winners have positive win margins (0 to 5) and losers have negative win margins (-5 to 0). Since <code>win_margin</code> has a negative coefficient of -1.46, the positive win margins of winners lower their predicted lifespans, while the negative win margins of losers increase their predicted lifespans, pulling the two group averages closer together.</p>
<p>In contrast, <code>avg_comparisons()</code> computes the average causal effect (treatment effect) by comparing the predicted lifespans under the ‘Win’ vs.&nbsp;‘Lose’ conditions for each candidate while holding all other covariates (including <code>win_margin</code>) constant. This isolates the true treatment coefficient of winning, which is <strong>8.63 years</strong>.</p>
</section>
<section id="visualizations" class="level3">
<h3 class="anchored" data-anchor-id="visualizations">Visualizations</h3>
<p>Create a visualization of the average predictions by election result using <code>plot_predictions()</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="governors-temperance_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What measure of uncertainty is shown in this plot?</p>
<p>The plot displays the <strong>95% confidence intervals</strong> around the average predictions, represented by the vertical error bars (point ranges).</p>
<p>Create a plot showing predicted years lived after the election as a function of <code>election_age</code>, separately for winners and losers.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="governors-temperance_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>How does the life insurer interpret the estimated effect of winning? How does the researcher interpret the same number differently?</p>
<ul>
<li><strong>Life Insurer (Predictive Interpretation):</strong> The insurer views the 8.6-year estimate purely as a predictive adjustment. Knowing that a Senate candidate won the election is a useful signal for forecasting their longevity. It does not matter <em>why</em> winners live longer, only that winning is a strong predictor to help price policies and manage liabilities.</li>
<li><strong>Researcher (Causal Interpretation):</strong> The researcher interprets the 8.6-year estimate as the average causal effect of winning office. Because close elections mimic a randomized experiment (a regression discontinuity design), they assume winning <em>causes</em> candidates to live longer, likely due to increased wealth, access to better healthcare, higher social status, or reduced stress.</li>
</ul>
</section>
<section id="humility" class="level3">
<h3 class="anchored" data-anchor-id="humility">Humility</h3>
<p>Besides the average years lived, identify two additional quantities of interest the person in your scenario might care about.</p>
<ul>
<li><strong>Life Insurer:</strong>
<ol type="1">
<li>The probability of surviving past a certain age threshold (e.g., 75 or 80 years) to price annuities.</li>
<li>The standard deviation or variance of post-election lifespans to assess risk and tail longevity probabilities.</li>
</ol></li>
<li><strong>Researcher:</strong>
<ol type="1">
<li>The heterogeneous treatment effects (e.g., does winning benefit younger candidates more than older ones, or Democrats more than Republicans?).</li>
<li>The effect of winning on health-adjusted life years (quality of life) rather than just raw lifespan.</li>
</ol></li>
</ul>
<p>Why might these estimates be a poor answer to your scenario’s question? Identify at least two possible sources of bias.</p>
<ul>
<li><strong>Life Insurer:</strong>
<ol type="1">
<li><strong>Representativeness Bias:</strong> The model is estimated on gubernatorial candidates from 1945–2012, which may not generalize to this year’s Senate candidates due to differences between offices and modern medical advancements.</li>
<li><strong>Selection Bias:</strong> The model is fit only on close elections (<span class="math inline">\(\le 5\%\)</span> margin). If the relationship between winning and longevity is different in landslide elections, the model will produce poor forecasts for candidates running in non-close races.</li>
</ol></li>
<li><strong>Researcher:</strong>
<ol type="1">
<li><strong>Generalizability Bias (External Validity):</strong> The causal effect for governors may not generalize to other elected offices like mayors or school board members, where the stress, resources, and prestige differ.</li>
<li><strong>Confounding Bias:</strong> Even in close elections, winning might not be perfectly random. If candidates who win close elections differ systematically from those who lose (e.g., having more physical resilience or better party support), unobserved factors could bias the causal estimate.</li>
</ol></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>